<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZfcUserImpersonate\Module'                                               => __DIR__ . '/Module.php',
    'ZfcUserImpersonate\Controller\User'                                      => __DIR__ . '/src/ZfcUserImpersonate/Controller/User.php',
    'ZfcUserImpersonate\Exception\Domain'                                     => __DIR__ . '/src/ZfcUserImpersonate/Exception/Domain.php',
    'ZfcUserImpersonate\Exception\NotImpersonating'                           => __DIR__ . '/src/ZfcUserImpersonate/Exception/NotImpersonating.php',
    'ZfcUserImpersonate\Exception\UserNotFound'                               => __DIR__ . '/src/ZfcUserImpersonate/Exception/UserNotFound.php',
    'ZfcUserImpersonate\Exception\ZfcUserImpersonate'                         => __DIR__ . '/src/ZfcUserImpersonate/Exception/ZfcUserImpersonate.php',
    'ZfcUserImpersonate\Module\AbstractModule'                                => __DIR__ . '/src/ZfcUserImpersonate/Module/AbstractModule.php',
    'ZfcUserImpersonate\ModuleManager\Feature\AutoloaderProviderDefaultTrait' => __DIR__ . '/src/ZfcUserImpersonate/ModuleManager/Feature/AutoloaderProviderDefaultTrait.php',
    'ZfcUserImpersonate\ModuleManager\Feature\ClassDirTrait'                  => __DIR__ . '/src/ZfcUserImpersonate/ModuleManager/Feature/ClassDirTrait.php',
    'ZfcUserImpersonate\ModuleManager\Feature\ClassNamespaceTrait'            => __DIR__ . '/src/ZfcUserImpersonate/ModuleManager/Feature/ClassNamespaceTrait.php',
    'ZfcUserImpersonate\ModuleManager\Feature\ConfigProviderTrait'            => __DIR__ . '/src/ZfcUserImpersonate/ModuleManager/Feature/ConfigProviderTrait.php',
    'ZfcUserImpersonate\ModuleManager\Feature\ControllerConfigProviderTrait'  => __DIR__ . '/src/ZfcUserImpersonate/ModuleManager/Feature/ControllerConfigProviderTrait.php',
    'ZfcUserImpersonate\ModuleManager\Feature\ServiceConfigProviderTrait'     => __DIR__ . '/src/ZfcUserImpersonate/ModuleManager/Feature/ServiceConfigProviderTrait.php',
    'ZfcUserImpersonate\ModuleManager\Feature\ViewHelperConfigProviderTrait'  => __DIR__ . '/src/ZfcUserImpersonate/ModuleManager/Feature/ViewHelperConfigProviderTrait.php',
    'ZfcUserImpersonate\Service\User'                                         => __DIR__ . '/src/ZfcUserImpersonate/Service/User.php',
    'ZfcUserImpersonate\View\Helper\ZfcUserImpersonatorDisplayName'           => __DIR__ . '/src/ZfcUserImpersonate/View/Helper/ZfcUserImpersonatorDisplayName.php',
    'ZfcUserImpersonate\View\Helper\ZfcUserImpersonatorIdentity'              => __DIR__ . '/src/ZfcUserImpersonate/View/Helper/ZfcUserImpersonatorIdentity.php',
);
