<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZfcUserImpersonate\Module'                                     => __DIR__ . '/Module.php',
    'ZfcUserImpersonate\Controller\User'                            => __DIR__ . '/src/ZfcUserImpersonate/Controller/User.php',
    'ZfcUserImpersonate\Exception\Domain'                           => __DIR__ . '/src/ZfcUserImpersonate/Exception/Domain.php',
    'ZfcUserImpersonate\Exception\NotImpersonating'                 => __DIR__ . '/src/ZfcUserImpersonate/Exception/NotImpersonating.php',
    'ZfcUserImpersonate\Exception\UserNotFound'                     => __DIR__ . '/src/ZfcUserImpersonate/Exception/UserNotFound.php',
    'ZfcUserImpersonate\Exception\ZfcUserImpersonate'               => __DIR__ . '/src/ZfcUserImpersonate/Exception/ZfcUserImpersonate.php',
    'ZfcUserImpersonate\Service\User'                               => __DIR__ . '/src/ZfcUserImpersonate/Service/User.php',
    'ZfcUserImpersonate\View\Helper\ZfcUserImpersonatorDisplayName' => __DIR__ . '/src/ZfcUserImpersonate/View/Helper/ZfcUserImpersonatorDisplayName.php',
    'ZfcUserImpersonate\View\Helper\ZfcUserImpersonatorIdentity'    => __DIR__ . '/src/ZfcUserImpersonate/View/Helper/ZfcUserImpersonatorIdentity.php',
);
